### ISSUE TITLE
ReadME issue

### ISSUE THREAD

**Issue by lijianyu1985** [Moh3nGolshani/BusyIndicator#12]
please change busyindicator:BusyMask to busyIndicator:BusyMask 

<busyindicator:BusyMask x:Name="BusyIndicator" IsBusy="False" IndicatorType="Dashes" BusyContent="Please wait..." >
         
         
          <... MAIN VIEW GOES HERE... >
         
         
</busyIndicator:BusyMask>

**Comment by Moh3nGolshani** [comment]
Thanks a lot
Done
