### ISSUE TITLE
IndicatorType "Swirl" is broken

### ISSUE THREAD

**Issue by gehho** [Moh3nGolshani/BusyIndicator#13]
Indicator type "Swirl" is broken. The circle is now completely blue with no visible animation.

It seems like it was introduced with the changes from 48bf107bb2972df5faacc40d0fade1fe1789b716. That commit introduced `IndicatorForeground` as a resource and replaced the `LinearGradientBrush`es from the `Swirl.xaml` template.

**Comment by Moh3nGolshani** [comment]
Hi
Fixed [check Demo app]
