### ISSUE TITLE
Is it possible to change the indicator size (height and width)?

### ISSUE THREAD

**Issue by alicetechnoprobe** [Moh3nGolshani/BusyIndicator#15]
Hello,
your library is really cool.  
Is there a way to change the size of the indicators?

Thank you.

**Comment by Moh3nGolshani** [comment]
Hi,

Unfortunately, there is no property to do that right now, but if you really need it, you can pull the repo and change the size of indicators (@BusyIndicator/Indicator/Resource/*.xaml), then rebuild the project and use a new generated BusyIndicator.dll in your project.

**Comment by alicetechnoprobe** [comment]
Ok, 
Thank you!

**Comment by Moh3nGolshani** [comment]
Check the new update.
