### ISSUE TITLE
Bind IsBusy not working

### ISSUE THREAD

**Issue by walterhuang** [Moh3nGolshani/BusyIndicator#17]
I try to do binding but not working. Did I miss anything? 

`<busyIndicator:BusyMask x:Name="BusyIndicator" IsBusy="{Binding IsBusy}" BusyContent="Please wait..." IndicatorType="Dashes">`

`public partial class MainWindow : Window, INotifyPropertyChanged
{
    public event PropertyChangedEventHandler PropertyChanged;

    protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }

    private bool _isBusy;

    public bool IsBusy
    {
        get => _isBusy;
        set { _isBusy = value; OnPropertyChanged(); }
    }

    public MainWindow()
    {
        InitializeComponent();
        IndicatorComboBox.SelectedIndex = 0;
        Stop();

        DataContext = this;
    }

    private async void Button_Click(object sender, RoutedEventArgs e)
    {
        if (!double.TryParse(MyTextBox.Text, out double duration))
        {
            duration = 10;
        }

        IsBusy = true;
        await Task.Delay(System.TimeSpan.FromSeconds(duration));
        IsBusy = false;
    }
}`

**Comment by Moh3nGolshani** [comment]
Hi
Change IsBusy="{Binding IsBusy}" to IsBusy="{Binding IsBusy, Mode=TwoWay}".
