### ISSUE TITLE
Binding IsBusy does not work 

### ISSUE THREAD

**Issue by jordiramon-mcr** [Moh3nGolshani/BusyIndicator#19]
If binding IsBusy with boolean property of MVVM and set this property to true, it does not activate IsBusy.
This is due to the line 'IsBusy = IsBusyAtStartup;' that breaks the binding.

```
public override void OnApplyTemplate()
{
    IsBusy = IsBusyAtStartup;
    ChangeVisualState(IsBusyAtStartup);
}
```

This could be solved by:

```
public override void OnApplyTemplate()
{
    if (IsBusyAtStartup) IsBusy = true;
    ChangeVisualState(IsBusyAtStartup);
}
```

**Comment by Moh3nGolshani** [comment]
Thanks a lot, I pushed the fix.
