### ISSUE TITLE
view use IsBusy  binding  prism's  mode value invalid

### ISSUE THREAD

**Issue by lzlige** [Moh3nGolshani/BusyIndicator#20]
Model value:
 public bool isMyBusy = false;
 public bool IsMyBusy
 {
     get
     {
         return isMyBusy;
     }
     set
     {
         if (isMyBusy == value)
         {
             return;
         }

         isMyBusy = value;
         RaisePropertyChanged("IsMyBusy");
     }
 }

view binding:
<xctk:BusyMask  x:Name="BusyIndicator"
      IsBusy="{Binding IsMyBusy,Mode=TwoWay}" BusyContent="Please wait......" FocusAfterBusy="{Binding ElementName=MyGrid}"
      BusyContentMargin="10" IndicatorType="Dashes" IsBusyAtStartup="False"></xctk:BusyMask>

**Comment by Moh3nGolshani** [comment]
Hi, please check the demo app for a working example or provide more information.

**Comment by lzlige** [comment]
IsBusyAtStartup="False"  can  show ,but IsBusy="{Binding IsMyBusy,Mode=TwoWay}"  can't show

**Comment by lzlige** [comment]
> Hi, please check the demo app for a working example or provide more information.

IsBusyAtStartup="False"  can  show ,but IsBusy="{Binding IsMyBusy,Mode=TwoWay}"  can't show

**Comment by Moh3nGolshani** [comment]
Which version of Prism are you currently using?
