### ISSUE TITLE
I binding Isbusy and it not working on fisrt time, it only working when I set isbusy = true in next turn

### ISSUE THREAD

**Issue by vanvu0211** [Moh3nGolshani/BusyIndicator#23]

**Comment by Moh3nGolshani** [comment]
If you mean it's not working at startup, you have to set IsBusyAtStartup = true.

**Comment by vu34304** [comment]
I install your nuget on: https://www.nuget.org/packages/BusyIndicators/2.1.0. But I cant use IsBusyAtStartup , it not have. 
![Uploading Screenshot 2024-04-26 014824.png…]()

**Comment by vanvu0211** [comment]
> If you mean it's not working at startup, you have to set IsBusyAtStartup = true.

Thank.
