### ISSUE TITLE
How to set focus to a control after is busy

### ISSUE THREAD

**Issue by Gerardo-Sista** [Moh3nGolshani/BusyIndicator#4]
Hello, 
your library is really cool.
Could you tell me how to set the focus to a control when IsBusy = false?

Is there a way to have a FocusAfterBusy property like the one in xceed toolkit? 

Thank you.

**Comment by Moh3nGolshani** [comment]
Hi
Currently there is no property like that, but I'll add this feature in the upcoming weeks. However, if you give your control a name, then you can use [YourControlName.Focus()] after setting IsBusy=false.

**Comment by Gerardo-Sista** [comment]
Thank you for reply. I'm using MVVM (most of developers use it). A property  like FocusAfterBusy = {Binding ElementName Mycontrol} could be the best option. Thank you.

**Comment by Moh3nGolshani** [comment]
Hi
I added FocusAfterBusy property, You can use it now [ FocusAfterBusy="{Binding ElementName = MyTextBox}" ].

**Comment by Gerardo-Sista** [comment]
Thank you!!!!
