### ISSUE TITLE
Indicators Not Working

### ISSUE THREAD

**Issue by iamsubingyawali** [Moh3nGolshani/BusyIndicator#6]
I am using this package in my WPF app with target .NET5. Here, only few indicators such as Swirl and Ellipse work and other indicators do not show up. Also, I can't change the color of the working indicators too. Is it due to my target framework or something else? Hoping a fix soon.

**Comment by Moh3nGolshani** [comment]
Hi
Sorry for responding too late, I added support for .NET 5, now it should work.

**Comment by iamsubingyawali** [comment]
Hi, Thanks for the response. It's working now. I closed the issue earlier as I thought this repo is no longer actively maintained.
