### ISSUE TITLE
BusyIndicator does not cover WindowsFormsHost controls.

### ISSUE THREAD

**Issue by EccoWorld** [Moh3nGolshani/BusyIndicator#9]
Hi Peoky,

I have wpf application that has both wpf controllers and form controllers. However, the busyindicator does not bring into the form controllers. For example,

![screenshot](https://user-images.githubusercontent.com/101242537/189918247-8b1ff8d8-a76a-43ff-987b-6c02a24a18da.PNG)

Thanks.

**Comment by Moh3nGolshani** [comment]
Hi
Sorry for the late reply. I’ll figure it out and push the fix.

**Comment by Moh3nGolshani** [comment]
Please check [this example](https://drive.google.com/file/d/1E75dNWAZWX6sf4GyDLxLUnoBN1NFNfRq/view?usp=sharing).
There is no problem with WindowsFormsHost!
